set mouse=a
set number
set ignorecase
set autoindent
set smartcase
set shell=zsh
set noeb vb t_vb=
let mapleader = ","

syntax on

set hlsearch "Highlights search terms"
set incsearch "Highlights search terms as you type them"
set showmatch "Highlights matching parentheses"

nnoremap <CR> :noh<CR>

" Bind ctrl+y copy to clipboard
vnoremap <C-y> :'<,'>w !xclip -selection clipboard<Cr><Cr>

" Allow crosshair cursor highlighting.
hi CursorLine   cterm=NONE ctermbg=0
hi CursorColumn cterm=NONE ctermbg=0
" set cursorline! cursorcolumn!
nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>
