set background=dark
set number
set ignorecase
set autoindent
set smartcase
set shell=zsh
set noeb vb t_vb=
let mapleader = ","

syntax on

hi Search term=bold ctermbg=cyan ctermfg=black
hi MatchParen ctermbg=black ctermfg=white
set hlsearch "Highlights search terms"
set incsearch "Highlights search terms as you type them"
set showmatch "Highlights matching parentheses"

" press Enter to remove highlights
nnoremap <CR> :noh<CR>

" bind ctrl+y copy to clipboard
vnoremap <C-y> :'<,'>w !xclip -selection clipboard<Cr><Cr>

" allow crosshair cursor highlighting
hi CursorLine   cterm=NONE ctermbg=0
hi CursorColumn cterm=NONE ctermbg=0

" toggle crosshair cursor
nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>
" toggle lines number
nnoremap <Leader>l :set number!<CR>

